name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B verify --file pom.xml


  Release:
      name: Release
      needs: [BuildAndTest]
      if: github.ref == 'refs/heads/master'
      uses: qcastel/github-actions-maven-release@master
      with:
        release-branch-name: "master"

        git-release-bot-name: "spds-release-bot"
        git-release-bot-email: "info@codeshield.de"

        access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}